title = "Scott Williams"
baseURL = "https://tocsoft.netlify.com"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Birkenhead, United Kingdom"
email = "tocsoft@gmail.com"
firstName = "Scott"
lastName = "Williams"
#phone = "1-555-555-1234"
profileImage = "img/profile.jpg"
showEducation = true
showExperience = true
showOpenSource = true
showProjects = true
showPublications = false
showQr = true
showSkills = true

[params.google]

[params.google.analytics]
trackerID = "UA-42193013-1"

[[params.handles]]
link = "https://www.linkedin.com/in/tocsoft"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/tocsoft/"
name = "GitHub"

[[params.handles]]
link = "https://twitter.com/tocsoft"
name = "Twitter"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"